import type { Vehicle } from "./vehicles.type";

const vehicles: Vehicle[] = [
  {
    id: "1",
    slug: "Audi RSQ8 Dynamik+ Keramik HuD 305kmh SoftClose Stand",
   bodyType: "SUV / Geländewagen / Pickup",
    brand: "Audi",
    model: "RSQ8",
    year: 12.2023,
    mileage: 24269 ,
    fuel: "petrol",
    gearbox: "auto",
    powerKW: 441,
    pricePerMonth: 0,
    priceTotal: 109990,
    priceNeto: 92429,
    images: [
      "/images/cars/audi-rsq8-2023/1.jpg",
      "/images/cars/audi-rsq8-2023/2.jpg",
      "/images/cars/audi-rsq8-2023/3.jpg",
      "/images/cars/audi-rsq8-2023/4.jpg",
      "/images/cars/audi-rsq8-2023/5.jpg",
      "/images/cars/audi-rsq8-2023/6.jpg",
      "/images/cars/audi-rsq8-2023/7.jpg",
      "/images/cars/audi-rsq8-2023/8.jpg",
      "/images/cars/audi-rsq8-2023/9.jpg",
      "/images/cars/audi-rsq8-2023/10.jpg",
      "/images/cars/audi-rsq8-2023/11.jpg",
      "/images/cars/audi-rsq8-2023/12.jpg",
      "/images/cars/audi-rsq8-2023/13.jpg",
      "/images/cars/audi-rsq8-2023/14.jpg",
      "/images/cars/audi-rsq8-2023/15.jpg",
      "/images/cars/audi-rsq8-2023/16.jpg",
      "/images/cars/audi-rsq8-2023/17.jpg",
      "/images/cars/audi-rsq8-2023/18.jpg",
      "/images/cars/audi-rsq8-2023/19.jpg",
      "/images/cars/audi-rsq8-2023/20.jpg",
    ],
    available: true,
    featured: true,
    technicalData: {
  "Baureihe": "RS Q8 (4MN) (08.2019 ->)",
  "Ausstattungslinie": "4.0 TFSI quattro",
  "Hubraum": "3.996 cm³",
  "Sitzplätze": "5",
  "Türen": "4/5",
  "Schadstoffklasse": "Euro 6d",
  "Umweltplakette": "4 (Grün)",
  "Fahrzeughalter": "1",
  "HU": "Neu",
  "Klimatisierung": "Klimaautomatik",
  "Einparkhilfe": "360°-Kamera, Vorne, Hinten",
  "Airbags": "Front-, Seiten- und weitere Airbags",
  "Farbe": "Daytonagrau Perleffekt",
  "Innenausstattung": "Vollleder, Schwarz",
  "Gewicht": "2.390 kg",
  "Zylinder": "8",
  "Antriebsart": "Verbrennungsmotor",
  "Energieverbrauch (komb.)": "13,2 l/100km",
  "CO₂-Emissionen (komb.)": "300 g/km",
},
    shortDesc: "Dynamik+ Keramik HuD 305kmh SoftClose Stand",
   },
  {
  id: "2",
  slug: "audi-s5-sportback-2024-competition",
  bodyType: "Limousine",
  brand: "Audi",
  model: "S5 Sportback Competition",
  year: 2024,
  mileage: 17074,
  fuel: "diesel",
  gearbox: "auto",    
  powerKW: 251,
  pricePerMonth: 0,  
  priceTotal: 59990,
  priceNeto: 50412,
  images: [
    "/images/cars/audi-s5-sportback-2024-competition/1.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/2.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/3.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/4.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/5.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/6.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/7.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/8.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/9.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/10.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/11.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/12.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/13.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/14.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/15.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/16.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/17.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/18.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/19.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/20.jpg",
  ],
  available: true,        
  featured: true,
  technicalData: {
  "Baureihe": "S5 Sportback (F5F) (10.2019 ->)",
  "Ausstattungslinie": "3.0 TDI quattro basis",
  "Hubraum": "2.967 cm³",
  "Sitzplätze": "5",
  "Türen": "4/5",
  "Schadstoffklasse": "Euro 6d",
  "Fahrzeughalter": "1",
  "HU": "08/2025",
  "Klimatisierung": "Klimaautomatik",
  "Einparkhilfe": "Hinten, Kamera, Vorne",
  "Airbags": "Front-, Seiten- und weitere Airbags",
  "Farbe": "Daytonagrau Perleffekt (Grau Metallic)",
  "Innenausstattung": "Teilleder",
  "Gewicht": "1.895 kg",
  "Zylinder": "6",
  "Antriebsart": "Verbrennungsmotor",
  "Energieverbrauch (komb.)": "7,1 l/100km",
  "CO₂-Emissionen (komb.)": "185 g/km"
},
  shortDesc: "Competition, B&O, Massage, Panorama, DAB.",
},
{
  id: "3",
  slug: "audi-s6-avant-2024-tdi-quattro",
  bodyType: "Kombi",
  brand: "Audi",
  model: "S6 3.0 TDI quattro Avant",
  year: 2024,
  mileage: 19490,
  fuel: "diesel",
  gearbox: "auto",           
  powerKW: 253,
  pricePerMonth: 0,          
  priceTotal: 66490,    
  priceNeto: 55874,       
  images: [
    "/images/cars/audi-s6-avant-2024/1.jpg",
    "/images/cars/audi-s6-avant-2024/2.jpg",
    "/images/cars/audi-s6-avant-2024/3.jpg",
    "/images/cars/audi-s6-avant-2024/4.jpg",
    "/images/cars/audi-s6-avant-2024/5.jpg",
    "/images/cars/audi-s6-avant-2024/6.jpg",
    "/images/cars/audi-s6-avant-2024/7.jpg",
    "/images/cars/audi-s6-avant-2024/8.jpg",
    "/images/cars/audi-s6-avant-2024/9.jpg",
    "/images/cars/audi-s6-avant-2024/10.jpg",
    "/images/cars/audi-s6-avant-2024/11.jpg",
    "/images/cars/audi-s6-avant-2024/12.jpg",
    "/images/cars/audi-s6-avant-2024/13.jpg",
    "/images/cars/audi-s6-avant-2024/14.jpg",
    "/images/cars/audi-s6-avant-2024/15.jpg",
    "/images/cars/audi-s6-avant-2024/16.jpg",
    "/images/cars/audi-s6-avant-2024/17.jpg",
    "/images/cars/audi-s6-avant-2024/18.jpg",
    "/images/cars/audi-s6-avant-2024/19.jpg",
    "/images/cars/audi-s6-avant-2024/20.jpg",
  ],
  available: true,            
  featured: true,
  shortDesc: "MATRIX, B&O, Panorama, AHK, ACC, Memory.",
  technicalData: {
    "Baureihe": "S6 Avant (4A5) (03.2019 ->)",
    "Ausstattungslinie": "3.0 TDI quattro basis",
    "Hubraum": "2.967 cm³",
    "Sitzplätze": "5",
    "Türen": "4/5",
    "Schadstoffklasse": "Euro 6d",
    "Fahrzeughalter": "1",
    "HU": "08/2025",
    "Klimatisierung": "Klimaautomatik",
    "Einparkhilfe": "Kamera, Vorne, Hinten",
    "Farbe": "Chronosgrau (Herstellerangabe)",
    "Innenausstattung": "Teilleder",
    "Gewicht": "2.095 kg",
    "Zylinder": "6",
    "Antriebsart": "Verbrennungsmotor",
    "Energieverbrauch (komb.)": "7,1 l/100km",
    "CO₂-Emissionen (komb.)": "186 g/km"
  }
},
{
  id: "4",
  slug: "audi-s6-limousine-2024-tdi-quattro",
  bodyType: "Limousine",
  brand: "Audi",
  model: "S6 3.0 TDI quattro Limousine",
  year: 2024,
  mileage: 18576,
  fuel: "diesel",
  gearbox: "auto",               
  powerKW: 253,
  pricePerMonth: 0,              
  priceTotal: 66490,  
  priceNeto: 55874,            
  images: [
    "/images/cars/audi-s6-limousine-2024/1.jpg",
    "/images/cars/audi-s6-limousine-2024/2.jpg",
    "/images/cars/audi-s6-limousine-2024/3.jpg",
    "/images/cars/audi-s6-limousine-2024/4.jpg",
    "/images/cars/audi-s6-limousine-2024/5.jpg",
    "/images/cars/audi-s6-limousine-2024/6.jpg",
    "/images/cars/audi-s6-limousine-2024/7.jpg",
    "/images/cars/audi-s6-limousine-2024/8.jpg",
    "/images/cars/audi-s6-limousine-2024/9.jpg",
    "/images/cars/audi-s6-limousine-2024/10.jpg",
    "/images/cars/audi-s6-limousine-2024/11.jpg",
    "/images/cars/audi-s6-limousine-2024/12.jpg",
    "/images/cars/audi-s6-limousine-2024/13.jpg",
    "/images/cars/audi-s6-limousine-2024/14.jpg",
    "/images/cars/audi-s6-limousine-2024/15.jpg",
    "/images/cars/audi-s6-limousine-2024/16.jpg",
    "/images/cars/audi-s6-limousine-2024/17.jpg",
    "/images/cars/audi-s6-limousine-2024/18.jpg",
    "/images/cars/audi-s6-limousine-2024/19.jpg",
    "/images/cars/audi-s6-limousine-2024/20.jpg",
  ],
  available: true,                
  featured: true,
  shortDesc: "schwarz+, Matrix, Panorama, Head-up, B&O, Rückfahrkamera.",
  technicalData: {
    "Baureihe": "S6 Lim. (4A2) (03.2019 ->)",
    "Ausstattungslinie": "3.0 TDI quattro basis",
    "Hubraum": "2.967 cm³",
    "Sitzplätze": "4",
    "Türen": "4/5",
    "Fahrzeughalter": "1",
    "HU": "06/2025",
    "Klimatisierung": "3-Zonen-Klimaautomatik",
    "Einparkhilfe": "Kamera, Vorne, Hinten",
    "Farbe": "Daytona (Grau Metallic)",
    "Innenausstattung": "Teilleder",
    "Gewicht": "2.030 kg",
    "Zylinder": "6",
    "Antriebsart": "Verbrennungsmotor",
    "Energieverbrauch (komb.)": "6,9 l/100km",
    "CO₂-Emissionen (komb.)": "182 g/km"
  }
},
{
  id: "5",
  slug: "bmw-520d-xdrive-2024-m-sport-touring",
  bodyType: "Kombi",
  brand: "BMW",
  model: "520 d xDrive M Sport",
  year: 2024,                
  mileage: 9999,              
  fuel: "diesel",
  gearbox: "auto",            
  powerKW: 145,              
  pricePerMonth: 0,         
  priceTotal: 52990,         
  priceNeto: 44529,           
  images: [
    "/images/cars/bmw-520d-xdrive-2024/1.jpg",
    "/images/cars/bmw-520d-xdrive-2024/2.jpg",
    "/images/cars/bmw-520d-xdrive-2024/3.jpg",
    "/images/cars/bmw-520d-xdrive-2024/4.jpg",
    "/images/cars/bmw-520d-xdrive-2024/5.jpg",
    "/images/cars/bmw-520d-xdrive-2024/6.jpg",
    "/images/cars/bmw-520d-xdrive-2024/7.jpg",
    "/images/cars/bmw-520d-xdrive-2024/8.jpg",
    "/images/cars/bmw-520d-xdrive-2024/9.jpg",
    "/images/cars/bmw-520d-xdrive-2024/10.jpg",
    "/images/cars/bmw-520d-xdrive-2024/11.jpg",
    "/images/cars/bmw-520d-xdrive-2024/12.jpg",
    "/images/cars/bmw-520d-xdrive-2024/13.jpg",
    "/images/cars/bmw-520d-xdrive-2024/14.jpg",
    "/images/cars/bmw-520d-xdrive-2024/15.jpg",
    "/images/cars/bmw-520d-xdrive-2024/16.jpg",
    "/images/cars/bmw-520d-xdrive-2024/17.jpg",
    "/images/cars/bmw-520d-xdrive-2024/18.jpg",
    "/images/cars/bmw-520d-xdrive-2024/19.jpg",
    "/images/cars/bmw-520d-xdrive-2024/20.jpg",
  ],
  available: true,          
  featured: true,
  shortDesc: "M Sport, 5-J. Service/60 Tkm, AHK, Autobahnassistent.",
  technicalData: {
    "Baureihe": "5 Touring (G61) (2024 ->)",
    "Ausstattungslinie": "520 d xDrive M Sport",
    "Hubraum": "1.995 cm³",
    "Sitzplätze": "5",
    "Türen": "4/5",
    "Fahrzeughalter": "1",
    "Erstzulassung": "08/2024",
    "HU": "Neu",
    "Klimatisierung": "Klimaautomatik",
    "Einparkhilfe": "360°-Kamera, Vorne, Selbstlenkende Systeme, Hinten",
    "Farbe (Hersteller)": "Brooklyn Grau",
    "Farbe": "Grau",
    "Innenausstattung": "Vollleder",
    "Gewicht": "1.970 kg",
    "Zylinder": "4",
    "Antriebsart": "Verbrennungsmotor",
    "Kraftstoffverbrauch (komb.)": "5,6 l/100km",
    "Kraftstoffverbrauch (Stadt)": "8,0 l/100km",
    "Kraftstoffverbrauch (Stadtrand)": "5,5 l/100km",
    "Kraftstoffverbrauch (Landstraße)": "4,9 l/100km",
    "Kraftstoffverbrauch (Autobahn)": "5,6 l/100km",
    "CO₂-Emissionen (komb.)": "149 g/km",
    "Fahrzeugzustand": "Gebrauchtfahrzeug, Unfallfrei",
    "Fahrzeugnummer": "4943"
  }
},
{
  id: "6",
  slug: "bmw-m4-competition-2016-carbon",
  bodyType: "Coupé",
  brand: "BMW",
  model: "M4 Competition Carbon",
  year: 2016,
  mileage: 33089,
  fuel: "petrol",
  gearbox: "auto",
  powerKW: 331,
  pricePerMonth: 0,
  priceTotal: 49990,
  priceNeto: 42008,
  images: [
    "/images/cars/bmw-m4-competition-2016/1.jpg",
    "/images/cars/bmw-m4-competition-2016/2.jpg",
    "/images/cars/bmw-m4-competition-2016/3.jpg",
    "/images/cars/bmw-m4-competition-2016/4.jpg",
    "/images/cars/bmw-m4-competition-2016/5.jpg",
    "/images/cars/bmw-m4-competition-2016/6.jpg",
    "/images/cars/bmw-m4-competition-2016/7.jpg",
    "/images/cars/bmw-m4-competition-2016/8.jpg",
    "/images/cars/bmw-m4-competition-2016/9.jpg",
    "/images/cars/bmw-m4-competition-2016/10.jpg",
    "/images/cars/bmw-m4-competition-2016/11.jpg",
    "/images/cars/bmw-m4-competition-2016/12.jpg",
    "/images/cars/bmw-m4-competition-2016/13.jpg",
    "/images/cars/bmw-m4-competition-2016/14.jpg",
    "/images/cars/bmw-m4-competition-2016/15.jpg",
    "/images/cars/bmw-m4-competition-2016/16.jpg",
    "/images/cars/bmw-m4-competition-2016/17.jpg",
    "/images/cars/bmw-m4-competition-2016/18.jpg",
    "/images/cars/bmw-m4-competition-2016/19.jpg",
    "/images/cars/bmw-m4-competition-2016/20.jpg",
  ],
  available: true,
  featured: true,
  shortDesc: "Competition, Carbon, Kamera, Memory.",
  technicalData: {
    "Baureihe": "M4 Coupe (F82) (2014 ->)",
    "Ausstattungslinie": "Basis",
    "Hubraum": "2.979 cm³",
    "Sitzplätze": "4",
    "Türen": "2/3",
    "Schadstoffklasse": "Euro 6",
    "Umweltplakette": "4 (Grün)",
    "Fahrzeughalter": "2",
    "Erstzulassung": "07/2016",
    "HU": "Neu",
    "Klimatisierung": "2-Zonen-Klimaautomatik",
    "Einparkhilfe": "Hinten, Kamera, Vorne",
    "Farbe (Hersteller)": "Sonderlackierung",
    "Farbe": "Schwarz Metallic",
    "Innenausstattung": "Vollleder, Schwarz",
    "Gewicht": "1.615 kg",
    "Letzte Wartung (Datum)": "09/2019",
    "Letzte Wartung (km)": "28.507 km",
    "Zylinder": "6",
    "Fahrzeugzustand": "Gebrauchtfahrzeug, Unfallfrei",
    "Ausführung": "Deutsche Ausführung",
    "Fahrzeugnummer": "5142"
  }
},
{
  id: "7",
  slug: "bmw-x5-m-competition-2022-skylounge-bw-softclose",
  bodyType: "SUV / Geländewagen / Pickup",
  brand: "BMW",
  model: "X5 M Competition",
  year: 2022,
  mileage: 77961,
  fuel: "petrol",
  gearbox: "auto",
  powerKW: 460,
  pricePerMonth: 0,
  priceTotal: 81490,
  priceNeto: 68479,
  images: [
    "/images/cars/bmw-x5m-competition-2022/1.jpg",
    "/images/cars/bmw-x5m-competition-2022/2.jpg",
    "/images/cars/bmw-x5m-competition-2022/3.jpg",
    "/images/cars/bmw-x5m-competition-2022/4.jpg",
    "/images/cars/bmw-x5m-competition-2022/5.jpg",
    "/images/cars/bmw-x5m-competition-2022/6.jpg",
    "/images/cars/bmw-x5m-competition-2022/7.jpg",
    "/images/cars/bmw-x5m-competition-2022/8.jpg",
    "/images/cars/bmw-x5m-competition-2022/9.jpg",
    "/images/cars/bmw-x5m-competition-2022/10.jpg",
    "/images/cars/bmw-x5m-competition-2022/11.jpg",
    "/images/cars/bmw-x5m-competition-2022/12.jpg",
    "/images/cars/bmw-x5m-competition-2022/13.jpg",
    "/images/cars/bmw-x5m-competition-2022/14.jpg",
    "/images/cars/bmw-x5m-competition-2022/15.jpg",
    "/images/cars/bmw-x5m-competition-2022/16.jpg",
    "/images/cars/bmw-x5m-competition-2022/17.jpg",
    "/images/cars/bmw-x5m-competition-2022/18.jpg",
    "/images/cars/bmw-x5m-competition-2022/19.jpg",
    "/images/cars/bmw-x5m-competition-2022/20.jpg"
  ],
  available: true,
  featured: true,
  shortDesc: "SkyLounge, B&W, Drivers Assistant, SoftClose.",
  technicalData: {
    "Baureihe": "X5 M (F95) (2019 ->)",
    "Ausstattungslinie": "Competition",
    "Hubraum": "4.395 cm³",
    "Sitzplätze": "5",
    "Türen": "4/5",
    "Schadstoffklasse": "Euro 6d",
    "Fahrzeughalter": "1",
    "Erstzulassung": "04/2022",
    "HU": "05/2027",
    "Klimatisierung": "Klimaautomatik",
    "Einparkhilfe": "Kamera, Vorne, Hinten",
    "Airbags": "Front-, Seiten- und weitere Airbags",
    "Farbe (Hersteller)": "Dravitgrau Metallic",
    "Farbe": "Grau Metallic",
    "Innenausstattung": "Vollleder",
    "Gewicht": "2.410 kg",
    "Letzte Wartung (Datum)": "04/2025",
    "Letzte Wartung (km)": "67.261 km",
    "Zylinder": "8",
    "Antriebsart": "Verbrennungsmotor",
    "Kraftstoffverbrauch (komb.)": "13,4 l/100km",
    "CO₂-Emissionen (komb.)": "303 g/km",
    "Fahrzeugzustand": "Gebrauchtfahrzeug",
    "Ausführung": "Deutsche Ausführung",
    "Fahrzeugnummer": "5110"
  }
}

];

export default vehicles;
