import type { Vehicle } from "./vehicles.type";

const vehicles: Vehicle[] = [
  {
    id: "1",
    slug: "Audi RSQ8 Dynamik+ Keramik HuD 305kmh SoftClose Stand",
   bodyType: "SUV / Geländewagen / Pickup",
    brand: "Audi",
    model: "RSQ8 Dynamik+ Keramik HuD 305kmh SoftClose Stand",
    year: 12.2023,
    mileage: 24269 ,
    fuel: "petrol",
    gearbox: "auto",
    powerKW: 441,
    pricePerMonth: 0,
    priceTotal: 109990,
    priceNeto: 92429,
    images: [
      "/images/cars/audi-rsq8-2023/1.jpg",
      "/images/cars/audi-rsq8-2023/2.jpg",
      "/images/cars/audi-rsq8-2023/3.jpg",
      "/images/cars/audi-rsq8-2023/4.jpg",
      "/images/cars/audi-rsq8-2023/5.jpg",
      "/images/cars/audi-rsq8-2023/6.jpg",
      "/images/cars/audi-rsq8-2023/7.jpg",
      "/images/cars/audi-rsq8-2023/8.jpg",
      "/images/cars/audi-rsq8-2023/9.jpg",
      "/images/cars/audi-rsq8-2023/10.jpg",
      "/images/cars/audi-rsq8-2023/11.jpg",
      "/images/cars/audi-rsq8-2023/12.jpg",
      "/images/cars/audi-rsq8-2023/13.jpg",
      "/images/cars/audi-rsq8-2023/14.jpg",
      "/images/cars/audi-rsq8-2023/15.jpg",
      "/images/cars/audi-rsq8-2023/16.jpg",
      "/images/cars/audi-rsq8-2023/17.jpg",
      "/images/cars/audi-rsq8-2023/18.jpg",
      "/images/cars/audi-rsq8-2023/19.jpg",
      "/images/cars/audi-rsq8-2023/20.jpg",
    ],
    available: true,
    featured: true,
    technicalData: {
  "Baureihe": "RS Q8 (4MN) (08.2019 ->)",
  "Ausstattungslinie": "4.0 TFSI quattro",
  "Hubraum": "3.996 cm³",
  "Sitzplätze": "5",
  "Türen": "4/5",
  "Schadstoffklasse": "Euro 6d",
  "Umweltplakette": "4 (Grün)",
  "Fahrzeughalter": "1",
  "HU": "Neu",
  "Klimatisierung": "Klimaautomatik",
  "Einparkhilfe": "360°-Kamera, Vorne, Hinten",
  "Airbags": "Front-, Seiten- und weitere Airbags",
  "Farbe": "Daytonagrau Perleffekt",
  "Innenausstattung": "Vollleder, Schwarz",
  "Gewicht": "2.390 kg",
  "Zylinder": "8",
  "Antriebsart": "Verbrennungsmotor",
  "Energieverbrauch (komb.)": "13,2 l/100km",
  "CO₂-Emissionen (komb.)": "300 g/km",
},
    shortDesc: "Dynamik+ Keramik HuD 305kmh SoftClose Stand",
   },
  {
  id: "2",
  slug: "audi-s5-sportback-2024-competition",
  bodyType: "Limousine",
  brand: "Audi",
  model: "S5 Competition B&O Massage PANORAMA DAB",
  year: 2024,
  mileage: 17074,
  fuel: "diesel",
  gearbox: "auto",    
  powerKW: 251,
  pricePerMonth: 0,  
  priceTotal: 59990,
  priceNeto: 50412,
  images: [
    "/images/cars/audi-s5-sportback-2024-competition/1.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/2.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/3.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/4.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/5.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/6.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/7.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/8.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/9.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/10.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/11.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/12.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/13.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/14.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/15.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/16.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/17.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/18.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/19.jpg",
    "/images/cars/audi-s5-sportback-2024-competition/20.jpg",
  ],
  available: true,        
  featured: true,
  technicalData: {
  "Baureihe": "S5 Sportback (F5F) (10.2019 ->)",
  "Ausstattungslinie": "3.0 TDI quattro basis",
  "Hubraum": "2.967 cm³",
  "Sitzplätze": "5",
  "Türen": "4/5",
  "Schadstoffklasse": "Euro 6d",
  "Fahrzeughalter": "1",
  "HU": "08/2025",
  "Klimatisierung": "Klimaautomatik",
  "Einparkhilfe": "Hinten, Kamera, Vorne",
  "Airbags": "Front-, Seiten- und weitere Airbags",
  "Farbe": "Daytonagrau Perleffekt (Grau Metallic)",
  "Innenausstattung": "Teilleder",
  "Gewicht": "1.895 kg",
  "Zylinder": "6",
  "Antriebsart": "Verbrennungsmotor",
  "Energieverbrauch (komb.)": "7,1 l/100km",
  "CO₂-Emissionen (komb.)": "185 g/km"
},
  shortDesc: "Competition, B&O, Massage, Panorama, DAB.",
},
{
  id: "3",
  slug: "audi-s6-avant-2024-tdi-quattro",
  bodyType: "Kombi",
  brand: "Audi",
  model: "S6 3.0TDI Quattro MATRIX B&O PANO AHK ACC MEMORY",
  year: 2024,
  mileage: 19490,
  fuel: "diesel",
  gearbox: "auto",           
  powerKW: 253,
  pricePerMonth: 0,          
  priceTotal: 66490,    
  priceNeto: 55874,       
  images: [
    "/images/cars/audi-s6-avant-2024/1.jpg",
    "/images/cars/audi-s6-avant-2024/2.jpg",
    "/images/cars/audi-s6-avant-2024/3.jpg",
    "/images/cars/audi-s6-avant-2024/4.jpg",
    "/images/cars/audi-s6-avant-2024/5.jpg",
    "/images/cars/audi-s6-avant-2024/6.jpg",
    "/images/cars/audi-s6-avant-2024/7.jpg",
    "/images/cars/audi-s6-avant-2024/8.jpg",
    "/images/cars/audi-s6-avant-2024/9.jpg",
    "/images/cars/audi-s6-avant-2024/10.jpg",
    "/images/cars/audi-s6-avant-2024/11.jpg",
    "/images/cars/audi-s6-avant-2024/12.jpg",
    "/images/cars/audi-s6-avant-2024/13.jpg",
    "/images/cars/audi-s6-avant-2024/14.jpg",
    "/images/cars/audi-s6-avant-2024/15.jpg",
    "/images/cars/audi-s6-avant-2024/16.jpg",
    "/images/cars/audi-s6-avant-2024/17.jpg",
    "/images/cars/audi-s6-avant-2024/18.jpg",
    "/images/cars/audi-s6-avant-2024/19.jpg",
    "/images/cars/audi-s6-avant-2024/20.jpg",
  ],
  available: true,            
  featured: true,
  shortDesc: "MATRIX, B&O, Panorama, AHK, ACC, Memory.",
  technicalData: {
    "Baureihe": "S6 Avant (4A5) (03.2019 ->)",
    "Ausstattungslinie": "3.0 TDI quattro basis",
    "Hubraum": "2.967 cm³",
    "Sitzplätze": "5",
    "Türen": "4/5",
    "Schadstoffklasse": "Euro 6d",
    "Fahrzeughalter": "1",
    "HU": "08/2025",
    "Klimatisierung": "Klimaautomatik",
    "Einparkhilfe": "Kamera, Vorne, Hinten",
    "Farbe": "Chronosgrau (Herstellerangabe)",
    "Innenausstattung": "Teilleder",
    "Gewicht": "2.095 kg",
    "Zylinder": "6",
    "Antriebsart": "Verbrennungsmotor",
    "Energieverbrauch (komb.)": "7,1 l/100km",
    "CO₂-Emissionen (komb.)": "186 g/km"
  }
},
{
  id: "4",
  slug: "audi-s6-limousine-2024-tdi-quattro",
  bodyType: "Limousine",
  brand: "Audi",
  model: "S6 TDI quattro schwarz+ Matrix Pano HuD B&O RFK",
  year: 2024,
  mileage: 18576,
  fuel: "diesel",
  gearbox: "auto",               
  powerKW: 253,
  pricePerMonth: 0,              
  priceTotal: 66490,  
  priceNeto: 55874,            
  images: [
    "/images/cars/audi-s6-limousine-2024/1.jpg",
    "/images/cars/audi-s6-limousine-2024/2.jpg",
    "/images/cars/audi-s6-limousine-2024/3.jpg",
    "/images/cars/audi-s6-limousine-2024/4.jpg",
    "/images/cars/audi-s6-limousine-2024/5.jpg",
    "/images/cars/audi-s6-limousine-2024/6.jpg",
    "/images/cars/audi-s6-limousine-2024/7.jpg",
    "/images/cars/audi-s6-limousine-2024/8.jpg",
    "/images/cars/audi-s6-limousine-2024/9.jpg",
    "/images/cars/audi-s6-limousine-2024/10.jpg",
    "/images/cars/audi-s6-limousine-2024/11.jpg",
    "/images/cars/audi-s6-limousine-2024/12.jpg",
    "/images/cars/audi-s6-limousine-2024/13.jpg",
    "/images/cars/audi-s6-limousine-2024/14.jpg",
    "/images/cars/audi-s6-limousine-2024/15.jpg",
    "/images/cars/audi-s6-limousine-2024/16.jpg",
    "/images/cars/audi-s6-limousine-2024/17.jpg",
    "/images/cars/audi-s6-limousine-2024/18.jpg",
    "/images/cars/audi-s6-limousine-2024/19.jpg",
    "/images/cars/audi-s6-limousine-2024/20.jpg",
  ],
  available: true,                
  featured: true,
  shortDesc: "schwarz+, Matrix, Panorama, Head-up, B&O, Rückfahrkamera.",
  technicalData: {
    "Baureihe": "S6 Lim. (4A2) (03.2019 ->)",
    "Ausstattungslinie": "3.0 TDI quattro basis",
    "Hubraum": "2.967 cm³",
    "Sitzplätze": "4",
    "Türen": "4/5",
    "Fahrzeughalter": "1",
    "HU": "06/2025",
    "Klimatisierung": "3-Zonen-Klimaautomatik",
    "Einparkhilfe": "Kamera, Vorne, Hinten",
    "Farbe": "Daytona (Grau Metallic)",
    "Innenausstattung": "Teilleder",
    "Gewicht": "2.030 kg",
    "Zylinder": "6",
    "Antriebsart": "Verbrennungsmotor",
    "Energieverbrauch (komb.)": "6,9 l/100km",
    "CO₂-Emissionen (komb.)": "182 g/km"
  }
},
{
  id: "5",
  slug: "bmw-520d-xdrive-2024-m-sport-touring",
  bodyType: "Kombi",
  brand: "BMW",
  model: "520 d xDr. M Sport 5J.Service/60Tkm AHK Autobahn",
  year: 2024,                
  mileage: 9999,              
  fuel: "diesel",
  gearbox: "auto",            
  powerKW: 145,              
  pricePerMonth: 0,         
  priceTotal: 52990,         
  priceNeto: 44529,           
  images: [
    "/images/cars/bmw-520d-xdrive-2024/1.jpg",
    "/images/cars/bmw-520d-xdrive-2024/2.jpg",
    "/images/cars/bmw-520d-xdrive-2024/3.jpg",
    "/images/cars/bmw-520d-xdrive-2024/4.jpg",
    "/images/cars/bmw-520d-xdrive-2024/5.jpg",
    "/images/cars/bmw-520d-xdrive-2024/6.jpg",
    "/images/cars/bmw-520d-xdrive-2024/7.jpg",
    "/images/cars/bmw-520d-xdrive-2024/8.jpg",
    "/images/cars/bmw-520d-xdrive-2024/9.jpg",
    "/images/cars/bmw-520d-xdrive-2024/10.jpg",
    "/images/cars/bmw-520d-xdrive-2024/11.jpg",
    "/images/cars/bmw-520d-xdrive-2024/12.jpg",
    "/images/cars/bmw-520d-xdrive-2024/13.jpg",
    "/images/cars/bmw-520d-xdrive-2024/14.jpg",
    "/images/cars/bmw-520d-xdrive-2024/15.jpg",
    "/images/cars/bmw-520d-xdrive-2024/16.jpg",
    "/images/cars/bmw-520d-xdrive-2024/17.jpg",
    "/images/cars/bmw-520d-xdrive-2024/18.jpg",
    "/images/cars/bmw-520d-xdrive-2024/19.jpg",
    "/images/cars/bmw-520d-xdrive-2024/20.jpg",
  ],
  available: true,          
  featured: true,
  shortDesc: "M Sport, 5-J. Service/60 Tkm, AHK, Autobahnassistent.",
  technicalData: {
    "Baureihe": "5 Touring (G61) (2024 ->)",
    "Ausstattungslinie": "520 d xDrive M Sport",
    "Hubraum": "1.995 cm³",
    "Sitzplätze": "5",
    "Türen": "4/5",
    "Fahrzeughalter": "1",
    "Erstzulassung": "08/2024",
    "HU": "Neu",
    "Klimatisierung": "Klimaautomatik",
    "Einparkhilfe": "360°-Kamera, Vorne, Selbstlenkende Systeme, Hinten",
    "Farbe (Hersteller)": "Brooklyn Grau",
    "Farbe": "Grau",
    "Innenausstattung": "Vollleder",
    "Gewicht": "1.970 kg",
    "Zylinder": "4",
    "Antriebsart": "Verbrennungsmotor",
    "Kraftstoffverbrauch (komb.)": "5,6 l/100km",
    "Kraftstoffverbrauch (Stadt)": "8,0 l/100km",
    "Kraftstoffverbrauch (Stadtrand)": "5,5 l/100km",
    "Kraftstoffverbrauch (Landstraße)": "4,9 l/100km",
    "Kraftstoffverbrauch (Autobahn)": "5,6 l/100km",
    "CO₂-Emissionen (komb.)": "149 g/km",
    "Fahrzeugzustand": "Gebrauchtfahrzeug, Unfallfrei",
    "Fahrzeugnummer": "4943"
  }
},
{
  id: "6",
  slug: "bmw-m4-competition-2016-carbon",
  bodyType: "Coupé",
  brand: "BMW",
  model: "M4 COMPETITON Carbon Kamera Memory",
  year: 2016,
  mileage: 33089,
  fuel: "petrol",
  gearbox: "auto",
  powerKW: 331,
  pricePerMonth: 0,
  priceTotal: 49990,
  priceNeto: 42008,
  images: [
    "/images/cars/bmw-m4-competition-2016/1.jpg",
    "/images/cars/bmw-m4-competition-2016/2.jpg",
    "/images/cars/bmw-m4-competition-2016/3.jpg",
    "/images/cars/bmw-m4-competition-2016/4.jpg",
    "/images/cars/bmw-m4-competition-2016/5.jpg",
    "/images/cars/bmw-m4-competition-2016/6.jpg",
    "/images/cars/bmw-m4-competition-2016/7.jpg",
    "/images/cars/bmw-m4-competition-2016/8.jpg",
    "/images/cars/bmw-m4-competition-2016/9.jpg",
    "/images/cars/bmw-m4-competition-2016/10.jpg",
    "/images/cars/bmw-m4-competition-2016/11.jpg",
    "/images/cars/bmw-m4-competition-2016/12.jpg",
    "/images/cars/bmw-m4-competition-2016/13.jpg",
    "/images/cars/bmw-m4-competition-2016/14.jpg",
    "/images/cars/bmw-m4-competition-2016/15.jpg",
    "/images/cars/bmw-m4-competition-2016/16.jpg",
    "/images/cars/bmw-m4-competition-2016/17.jpg",
    "/images/cars/bmw-m4-competition-2016/18.jpg",
    "/images/cars/bmw-m4-competition-2016/19.jpg",
    "/images/cars/bmw-m4-competition-2016/20.jpg",
  ],
  available: true,
  featured: true,
  shortDesc: "Competition, Carbon, Kamera, Memory.",
  technicalData: {
    "Baureihe": "M4 Coupe (F82) (2014 ->)",
    "Ausstattungslinie": "Basis",
    "Hubraum": "2.979 cm³",
    "Sitzplätze": "4",
    "Türen": "2/3",
    "Schadstoffklasse": "Euro 6",
    "Umweltplakette": "4 (Grün)",
    "Fahrzeughalter": "2",
    "Erstzulassung": "07/2016",
    "HU": "Neu",
    "Klimatisierung": "2-Zonen-Klimaautomatik",
    "Einparkhilfe": "Hinten, Kamera, Vorne",
    "Farbe (Hersteller)": "Sonderlackierung",
    "Farbe": "Schwarz Metallic",
    "Innenausstattung": "Vollleder, Schwarz",
    "Gewicht": "1.615 kg",
    "Letzte Wartung (Datum)": "09/2019",
    "Letzte Wartung (km)": "28.507 km",
    "Zylinder": "6",
    "Fahrzeugzustand": "Gebrauchtfahrzeug, Unfallfrei",
    "Ausführung": "Deutsche Ausführung",
    "Fahrzeugnummer": "5142"
  }
},
{
  id: "7",
  slug: "bmw-x5-m-competition-2022-skylounge-bw-softclose",
  bodyType: "SUV / Geländewagen / Pickup",
  brand: "BMW",
  model: "X5 M Competition SkyLounge B&W Drivers SoftClose",
  year: 2022,
  mileage: 77961,
  fuel: "petrol",
  gearbox: "auto",
  powerKW: 460,
  pricePerMonth: 0,
  priceTotal: 81490,
  priceNeto: 68479,
  images: [
    "/images/cars/bmw-x5m-competition-2022/1.jpg",
    "/images/cars/bmw-x5m-competition-2022/2.jpg",
    "/images/cars/bmw-x5m-competition-2022/3.jpg",
    "/images/cars/bmw-x5m-competition-2022/4.jpg",
    "/images/cars/bmw-x5m-competition-2022/5.jpg",
    "/images/cars/bmw-x5m-competition-2022/6.jpg",
    "/images/cars/bmw-x5m-competition-2022/7.jpg",
    "/images/cars/bmw-x5m-competition-2022/8.jpg",
    "/images/cars/bmw-x5m-competition-2022/9.jpg",
    "/images/cars/bmw-x5m-competition-2022/10.jpg",
    "/images/cars/bmw-x5m-competition-2022/11.jpg",
    "/images/cars/bmw-x5m-competition-2022/12.jpg",
    "/images/cars/bmw-x5m-competition-2022/13.jpg",
    "/images/cars/bmw-x5m-competition-2022/14.jpg",
    "/images/cars/bmw-x5m-competition-2022/15.jpg",
    "/images/cars/bmw-x5m-competition-2022/16.jpg",
    "/images/cars/bmw-x5m-competition-2022/17.jpg",
    "/images/cars/bmw-x5m-competition-2022/18.jpg",
    "/images/cars/bmw-x5m-competition-2022/19.jpg",
    "/images/cars/bmw-x5m-competition-2022/20.jpg"
  ],
  available: true,
  featured: false,
  shortDesc: "SkyLounge, B&W, Drivers Assistant, SoftClose.",
  technicalData: {
    "Baureihe": "X5 M (F95) (2019 ->)",
    "Ausstattungslinie": "Competition",
    "Hubraum": "4.395 cm³",
    "Sitzplätze": "5",
    "Türen": "4/5",
    "Schadstoffklasse": "Euro 6d",
    "Fahrzeughalter": "1",
    "Erstzulassung": "04/2022",
    "HU": "05/2027",
    "Klimatisierung": "Klimaautomatik",
    "Einparkhilfe": "Kamera, Vorne, Hinten",
    "Airbags": "Front-, Seiten- und weitere Airbags",
    "Farbe (Hersteller)": "Dravitgrau Metallic",
    "Farbe": "Grau Metallic",
    "Innenausstattung": "Vollleder",
    "Gewicht": "2.410 kg",
    "Letzte Wartung (Datum)": "04/2025",
    "Letzte Wartung (km)": "67.261 km",
    "Zylinder": "8",
    "Antriebsart": "Verbrennungsmotor",
    "Kraftstoffverbrauch (komb.)": "13,4 l/100km",
    "CO₂-Emissionen (komb.)": "303 g/km",
    "Fahrzeugzustand": "Gebrauchtfahrzeug",
    "Ausführung": "Deutsche Ausführung",
    "Fahrzeugnummer": "5110"
  }
},
{
  id: "8",
  slug: "bmw-ix1-30-xdrive-shadowline-innovationsp-curved",
  bodyType: "SUV / Geländewagen / Pickup",
  brand: "BMW",
  model: "iX1 30 xDrive Shadow-Line Innovations-P. CURVED",
  year: 2023,
  mileage: 35274,
  fuel: "electric",
  gearbox: "auto",
  powerKW: 230,
  pricePerMonth: 0,
  priceTotal: 33990,
  priceNeto: 28563,
  images: [
    "/images/cars/bmw-ix1-2023/1.jpg",
    "/images/cars/bmw-ix1-2023/2.jpg",
    "/images/cars/bmw-ix1-2023/3.jpg",
    "/images/cars/bmw-ix1-2023/4.jpg",
    "/images/cars/bmw-ix1-2023/5.jpg",
    "/images/cars/bmw-ix1-2023/6.jpg",
    "/images/cars/bmw-ix1-2023/7.jpg",
    "/images/cars/bmw-ix1-2023/8.jpg",
    "/images/cars/bmw-ix1-2023/9.jpg",
    "/images/cars/bmw-ix1-2023/10.jpg",
    "/images/cars/bmw-ix1-2023/11.jpg",
    "/images/cars/bmw-ix1-2023/12.jpg",
    "/images/cars/bmw-ix1-2023/13.jpg",
    "/images/cars/bmw-ix1-2023/14.jpg",
    "/images/cars/bmw-ix1-2023/15.jpg",
    "/images/cars/bmw-ix1-2023/16.jpg",
    "/images/cars/bmw-ix1-2023/17.jpg",
    "/images/cars/bmw-ix1-2023/18.jpg",
    "/images/cars/bmw-ix1-2023/19.jpg",
    "/images/cars/bmw-ix1-2023/20.jpg",
  ],
  available: true,
  featured: false,
  shortDesc: "Shadow-Line, Innovationspaket, Curved Display, 417 km Reichweite.",
  technicalData: {
    "Baureihe": "iX1 (U11E) (2022 ->)",
    "Ausstattungslinie": "30 xDrive",
    "Erstzulassung": "05/2023",
    "Sitzplätze": "5",
    "Türen": "4/5",
    "Umweltplakette": "4 (Grün)",
    "Fahrzeughalter": "1",
    "HU": "05/2026",
    "Klimatisierung": "2-Zonen-Klimaautomatik",
    "Einparkhilfe": "Vorne, 360°-Kamera, Hinten",
    "Farbe": "Schwarz II",
    "Innenausstattung": "Stoff, Schwarz",
    "Gewicht": "2.085 kg",
    "Leistung": "230 kW / 313 PS",
    "Reichweite": "417 km",
    "Letzte Wartung (Datum)": "05/2023",
    "Letzte Wartung (km)": "5 km",
    "Antriebsart": "Elektromotor",
    "Energieverbrauch (komb.)": "16,8 kWh/100km",
    "CO₂-Emissionen (komb.)": "10 g/km",
  },
},
{
  id: "9",
  slug: "ford-transit-hochraum-350l3-9sitze-rollstuhlrampe",
  bodyType: "Van / Minibus",
  brand: "Ford",
  model: "Transit Hochraum 350 L3 9 Sitze Rollstuhlrampe",
  year: 2020,
  mileage: 111611,
  fuel: "diesel",
  gearbox: "manual",
  powerKW: 96,
  pricePerMonth: 0,
  priceTotal: 27990,
  priceNeto: 23521,
  images: [
    "/images/cars/ford-transit-2020/1.jpg",
    "/images/cars/ford-transit-2020/2.jpg",
    "/images/cars/ford-transit-2020/3.jpg",
    "/images/cars/ford-transit-2020/4.jpg",
    "/images/cars/ford-transit-2020/5.jpg",
    "/images/cars/ford-transit-2020/6.jpg",
    "/images/cars/ford-transit-2020/7.jpg",
    "/images/cars/ford-transit-2020/8.jpg",
    "/images/cars/ford-transit-2020/9.jpg",
    "/images/cars/ford-transit-2020/10.jpg",
    "/images/cars/ford-transit-2020/11.jpg",
    "/images/cars/ford-transit-2020/12.jpg",
    "/images/cars/ford-transit-2020/13.jpg",
    "/images/cars/ford-transit-2020/14.jpg",
    "/images/cars/ford-transit-2020/15.jpg",
    "/images/cars/ford-transit-2020/16.jpg",
    "/images/cars/ford-transit-2020/17.jpg",
    "/images/cars/ford-transit-2020/18.jpg",
    "/images/cars/ford-transit-2020/19.jpg",
    "/images/cars/ford-transit-2020/20.jpg",
  ],
  available: true,
  featured: false,
  shortDesc: "9-Sitzer, Rollstuhlrampe, Trend Ausstattung, HU 01/2026.",
  technicalData: {
    "Baureihe": "Transit Kombi (TTS) (2019 ->)",
    "Ausstattungslinie": "350 L3 Trend",
    "Erstzulassung": "12/2020",
    "Sitzplätze": "9",
    "Türen": "4/5",
    "Schadstoffklasse": "Euro 6d-TEMP",
    "Umweltplakette": "4 (Grün)",
    "Fahrzeughalter": "1",
    "HU": "01/2026",
    "Klimatisierung": "Klimaanlage",
    "Einparkhilfe": "Hinten",
    "Farbe": "Frost-Weiß",
    "Innenausstattung": "Stoff, Schwarz",
    "Gewicht": "4.430 kg",
    "Leistung": "96 kW / 131 PS",
    "Hubraum": "1.995 cm³",
    "Letzte Wartung (Datum)": "01/2025",
    "Letzte Wartung (km)": "109.790 km",
    "Zylinder": "4",
    "Antriebsart": "Verbrennungsmotor",
  },
},
{
  id: "10",
  slug: "landrover-discovery-sport-dynamicse-awd-pano-20zoll-acc",
  bodyType: "SUV / Geländewagen / Pickup",
  brand: "Land Rover",
  model: "Discovery Sport Dynamic SE AWD PANO 20Zoll ACC",
  year: 2024,
  mileage: 19880,
  fuel: "diesel",
  gearbox: "auto",
  powerKW: 150,
  pricePerMonth: 0,
  priceTotal: 46990,
  priceNeto: 39487,
  images: [
    "/images/cars/landrover-discovery-sport-2024/1.jpg",
    "/images/cars/landrover-discovery-sport-2024/2.jpg",
    "/images/cars/landrover-discovery-sport-2024/3.jpg",
    "/images/cars/landrover-discovery-sport-2024/4.jpg",
    "/images/cars/landrover-discovery-sport-2024/5.jpg",
    "/images/cars/landrover-discovery-sport-2024/6.jpg",
    "/images/cars/landrover-discovery-sport-2024/7.jpg",
    "/images/cars/landrover-discovery-sport-2024/8.jpg",
    "/images/cars/landrover-discovery-sport-2024/9.jpg",
    "/images/cars/landrover-discovery-sport-2024/10.jpg",
    "/images/cars/landrover-discovery-sport-2024/11.jpg",
    "/images/cars/landrover-discovery-sport-2024/12.jpg",
    "/images/cars/landrover-discovery-sport-2024/13.jpg",
    "/images/cars/landrover-discovery-sport-2024/14.jpg",
    "/images/cars/landrover-discovery-sport-2024/15.jpg",
    "/images/cars/landrover-discovery-sport-2024/16.jpg",
    "/images/cars/landrover-discovery-sport-2024/17.jpg",
    "/images/cars/landrover-discovery-sport-2024/18.jpg",
    "/images/cars/landrover-discovery-sport-2024/19.jpg",
    "/images/cars/landrover-discovery-sport-2024/20.jpg",
  ],
  available: true,
  featured: false,
  shortDesc: "Dynamic SE, Panorama, 20 Zoll, ACC, HU 07/2027.",
  technicalData: {
    "Baureihe": "Discovery Sport (02.2015 ->)",
    "Ausstattungslinie": "Dynamic SE AWD",
    "Erstzulassung": "07/2024",
    "Sitzplätze": "5",
    "Türen": "4/5",
    "Schadstoffklasse": "Euro 6d",
    "Fahrzeughalter": "1",
    "HU": "07/2027",
    "Klimatisierung": "Klimaautomatik",
    "Einparkhilfe": "Kamera",
    "Farbe": "Santorini Black",
    "Innenausstattung": "Vollleder",
    "Gewicht": "1.949 kg",
    "Leistung": "150 kW / 204 PS",
    "Hubraum": "1.998 cm³",
    "Zylinder": "4",
    "Antriebsart": "Verbrennungsmotor",
    "Energieverbrauch (komb.)": "7,1 l/100km",
    "CO₂-Emissionen (komb.)": "187 g/km",
  },
},
{
  id: "11",
  slug: "landrover-rangeroversport-dynamichse-pano-pixel",
  bodyType: "SUV / Geländewagen / Pickup",
  brand: "Land Rover",
  model: "Range Rover Sport Dynamic HSE Pano PIXEL",
  year: 2024,
  mileage: 2084,
  fuel: "diesel",
  gearbox: "auto",
  powerKW: 221,
  pricePerMonth: 0,
  priceTotal: 109990,
  priceNeto: 92429,
  images: [
    "/images/cars/landrover-rangeroversport-2024/1.jpg",
    "/images/cars/landrover-rangeroversport-2024/2.jpg",
    "/images/cars/landrover-rangeroversport-2024/3.jpg",
    "/images/cars/landrover-rangeroversport-2024/4.jpg",
    "/images/cars/landrover-rangeroversport-2024/5.jpg",
    "/images/cars/landrover-rangeroversport-2024/6.jpg",
    "/images/cars/landrover-rangeroversport-2024/7.jpg",
    "/images/cars/landrover-rangeroversport-2024/8.jpg",
    "/images/cars/landrover-rangeroversport-2024/9.jpg",
    "/images/cars/landrover-rangeroversport-2024/10.jpg",
    "/images/cars/landrover-rangeroversport-2024/11.jpg",
    "/images/cars/landrover-rangeroversport-2024/12.jpg",
    "/images/cars/landrover-rangeroversport-2024/13.jpg",
    "/images/cars/landrover-rangeroversport-2024/14.jpg",
    "/images/cars/landrover-rangeroversport-2024/15.jpg",
    "/images/cars/landrover-rangeroversport-2024/16.jpg",
    "/images/cars/landrover-rangeroversport-2024/17.jpg",
    "/images/cars/landrover-rangeroversport-2024/18.jpg",
    "/images/cars/landrover-rangeroversport-2024/19.jpg",
    "/images/cars/landrover-rangeroversport-2024/20.jpg",
  ],
  available: true,
  featured: true,
  shortDesc: "Dynamic HSE, Panorama, Pixel-LED, 2.084 km, HU 04/2027.",
  technicalData: {
    "Baureihe": "Range Rover Sport (L461) (2022 ->)",
    "Ausstattungslinie": "Dynamic HSE",
    "Erstzulassung": "04/2024",
    "Sitzplätze": "5",
    "Türen": "4/5",
    "Schadstoffklasse": "Euro 6d",
    "Umweltplakette": "4 (Grün)",
    "Fahrzeughalter": "1",
    "HU": "04/2027",
    "Klimatisierung": "2-Zonen-Klimaautomatik",
    "Einparkhilfe": "Selbstlenkende Systeme, Hinten, Vorne, 360°-Kamera",
    "Airbags": "Front-, Seiten- und weitere Airbags",
    "Farbe": "Santorini Black",
    "Innenausstattung": "Vollleder, Schwarz",
    "Gewicht": "2.390 kg",
    "Leistung": "221 kW / 300 PS",
    "Hubraum": "2.997 cm³",
    "Zylinder": "6",
    "Antriebsart": "Verbrennungsmotor",
    "Energieverbrauch (komb.)": "8,0 l/100km",
    "CO₂-Emissionen (komb.)": "211 g/km",
  },
},


];

export default vehicles;
